name: CI
on: [pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test:schema
      - run: pnpm test:golden
      - run: pnpm check-import-fences
      - run: pnpm check-single-app
